### ISSUE TITLE
echo.cc编译错误

### ISSUE THREAD

**Issue by lghelp** [chenshuo/muduo-tutorial#2]
CMakeFiles/echo.dir/home/lgh/dbbase/src/echo.cc.o: In function `setLogging(char const*)':
/home/lgh/dbbase/src/echo.cc:74: undefined reference to `muduo::AsyncLogging::AsyncLogging(__gnu_cxx::__versa_string<char, std::char_traits<char>, std::allocator<char>, __gnu_cxx::__sso_string_base> const&, long, int)'

**Comment by zlonqi** [comment]
> CMakeFiles/echo.dir/home/lgh/dbbase/src/echo.cc.o: In function `setLogging(char const*)': /home/lgh/dbbase/src/echo.cc:74: undefined reference to `muduo::AsyncLogging::AsyncLogging(__gnu_cxx::__versa_string<char, std::char_traits, std::allocator, __gnu_cxx::__sso_string_base> const&, long, in
 @chenshuo
