### ISSUE TITLE
编译出错

### ISSUE THREAD

**Issue by samuelyao314** [chenshuo/muduo-tutorial#3]
samuel@bazel$ bazel build ...
Starting local Bazel server and connecting to it...
INFO: SHA256 (https://github.com/chenshuo/muduo/archive/master.zip) = 321ce19134deed89a7d99d4a9edd51d80174d0283290716e7a5ac519b4f4042c
DEBUG: Rule 'muduo' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = "321ce19134deed89a7d99d4a9edd51d80174d0283290716e7a5ac519b4f4042c"
INFO: Analysed target //:echo (12 packages loaded, 206 targets configured).
INFO: Found 1 target...
ERROR: /private/var/tmp/_bazel_samuel/82ad9d1260b40bf0bd586e86a97b7568/external/muduo/muduo/net/BUILD.bazel:1:1: C++ compilation of rule '@muduo//muduo/net:net' failed (Exit 1) wrapped_clang failed: error executing command external/local_config_cc/wrapped_clang '-D_FORTIFY_SOURCE=1' -fstack-protector -fcolor-diagnostics -Wall -Wthread-safety -Wself-assign -fno-omit-frame-pointer -O0 -DDEBUG '-std=c++11' -iquote ... (remaining 21 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
In file included from external/muduo/muduo/net/InetAddress.cc:11:
In file included from external/muduo/muduo/base/Logging.h:10:
external/muduo/muduo/base/Timestamp.h:12:10: fatal error: 'boost/operators.hpp' file not found
#include <boost/operators.hpp>
         ^~~~~~~~~~~~~~~~~~~~~
1 error generated.
Target //:echo failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 9.057s, Critical Path: 0.54s
INFO: 0 processes.
FAILED: Build did NOT complete successfully

我的macos 上是安装了boost的。 
samuel@bazel$ brew info boost
boost: stable 1.67.0 (bottled), HEAD
Collection of portable C++ source libraries
https://www.boost.org/
Not installed
From: https://mirrors.aliyun.com/homebrew/homebrew-core.git/Formula/boost.rb
==> Dependencies
Optional: icu4c ✔
==> Options
--with-icu4c
	Build regexp engine with icu support
--without-single
	Disable building single-threading variant
--without-static
	Disable building static library variant
--HEAD
	Install HEAD version
==> Caveats
Building of Boost.Log is disabled because it requires newer GCC or Clang.
==> Analytics
install: 67,653 (30d), 163,931 (90d), 660,447 (365d)
install_on_request: 22,428 (30d), 52,303 (90d), 199,309 (365d)
build_error: 0 (30d)

**Comment by chenshuo** [comment]
mac OS is not supported.
btw, this looks like incompatibility between bazel and brew, you should probably report bugs in bazel instead.
